name: admin_portal_mantis_pro_gaming
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  asn1lib: ^1.5.3
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  client_information: ^2.1.4
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get_ip_address: ^0.0.7
  get_it: ^7.7.0
  getwidget: ^4.0.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+1
  http: ^1.2.1
  intl: ^0.19.0
  mocktail: ^1.0.3
  oktoast: ^3.4.0
  path_provider: ^2.1.2
  pointycastle: ^3.9.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3




dev_dependencies:
  build_runner: ^2.4.10
  dart_mappable_builder: ^4.2.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg_images/
    - assets/icons/



























