import 'package:dart_mappable/dart_mappable.dart';

//generated by dart_mappable
part 'exceptions.mapper.dart';

@MappableClass()
class ServerException with ServerExceptionMappable implements Exception {
  const ServerException({required this.message, required this.statusCode});

  final String message;
  final String statusCode;
}

@MappableClass()
class CacheException with CacheExceptionMappable implements Exception {
  const CacheException({required this.message, this.statusCode = '500'});

  final String message;
  final String statusCode;
}
